
  0%|          | 0/1798 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Muhammad Talha Imran\PycharmProjects\CV_Assignment_2\SCR\MobileNetV3.py", line 135, in <module>
    train_loss, classification_loss, arousal_loss, valence_loss, train_accuracy = run_epoch(mobilenet,
  File "C:\Users\Muhammad Talha Imran\PycharmProjects\CV_Assignment_2\SCR\HelperFunctions.py", line 61, in run_epoch
    classification_loss = loss_weights[0] * classification_loss_function(output_class, label)
  File "C:\Users\Muhammad Talha Imran\anaconda3\envs\py_3\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Muhammad Talha Imran\anaconda3\envs\py_3\lib\site-packages\torch\nn\modules\loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "C:\Users\Muhammad Talha Imran\anaconda3\envs\py_3\lib\site-packages\torch\nn\functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_nll_loss_forward)